name: "Issues"

on:
  issues: 
    type: [opened]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: ./
        with:
          githubToken: ${{ secrets.GITHUBTOKEN }}
